### ISSUE TITLE
DesignSpace function $optimal() calls older version of function

### ISSUE THREAD

**Issue by samuel-watson** [samuel-watson/glmmr#16]
Does the function $optimal() call the right version of the grad robust function? Can @ypan1988 check and fix or close issue?

**Comment by ypan1988** [comment]
Sure. I will have a check today.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by samuel-watson** [comment]
Hi @ypan1988 can you confirm? I need to generate some test outputs for a demonstration and want to make sure that grad_robust_step() is the right function and is calling the appropriate cpp function.

**Comment by ypan1988** [comment]
Hi @samuel-watson . Sorry for the delay. At moment, duplicated R code is not removed yet. Hence C++ function can be called exactly the same way we call R function using grad_robust2_step().

**Comment by samuel-watson** [comment]
so what is the function name for the cpp version? GradRobustStep or grad_robust2_step?

**Comment by ypan1988** [comment]
In R environment:
# call R function
d4 <- grad_robust_step(idx_in,
                       C=list(dat1[[1]]),
                       X_list=list(dat1[[2]]),
                       sig_list = list(dat1[[3]]),
                       rm_cols=list(c(1,7)))
# call C++ function internally
d6 <- grad_robust2_step(idx_in,
                       C=list(dat1[[1]]),
                       X_list=list(dat1[[2]]),
                       sig_list = list(dat1[[3]]),
                       rm_cols=list(c(1,7)))

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ypan1988** [comment]
Please check the following line:

https://github.com/samuel-watson/glmmr/blob/main/R/gd_search.R#L852

it is the place where function grad_robust2_step() will call C++ function GradRobustStep().

________________________________
From: Yi Pan (Applied Health Research)
Sent: 06 March 2022 21:12:56
To: samuel-watson/glmmr
Subject: RE: [samuel-watson/glmmr] DesignSpace function $optimal() calls older version of function (Issue #16)

In R environment:
# call R function
d4 <- grad_robust_step(idx_in,
                       C=list(dat1[[1]]),
                       X_list=list(dat1[[2]]),
                       sig_list = list(dat1[[3]]),
                       rm_cols=list(c(1,7)))
# call C++ function internally
d6 <- grad_robust2_step(idx_in,
                       C=list(dat1[[1]]),
                       X_list=list(dat1[[2]]),
                       sig_list = list(dat1[[3]]),
                       rm_cols=list(c(1,7)))

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by samuel-watson** [comment]
Thanks @ypan1988 I will update code and close issue
