### ISSUE TITLE
Allow for fixed observations in optimal algorithm

### ISSUE THREAD

**Issue by samuel-watson** [samuel-watson/glmmr#3]
The optimal design algorithm should allow for an input that specifies that some observations must be in the design and cannot be removed

**Comment by ypan1988** [comment]
Sam, I have updated the code in the repo "codco" for fixing some observations using the existing two algorithms. Actually the one I implemented is a simpler version: use variable "nfix" to indicate that the first n observations in idx_in will be fixed. Hence R code need to determine the number of observation which will be fixed and make sure that the fixed observations are in the front. Changes are made in file gd_search.cpp & gd_search.R. It takes too long to compile the glmmr package after introducing the Stan code and we can simply replace these two files in glmmr later.

**Comment by samuel-watson** [comment]
Thank @ypan1988 that sounds like a good way to do it, good idea. Will add a note to the other issue. Can you update on this repo though please so I can close the issue and we can test with this infrastructure? Once you've compiled it once it won't need doing again really for Stan. Think it normally takes 5 - 10 mins. Could just push changes to these two files?
