### ISSUE TITLE
Translate permutation_test() and conf_int_search() to c++

### ISSUE THREAD

**Issue by samuel-watson** [samuel-watson/glmmr#36]
This would need a GLM library - the package could require fastglm https://github.com/jaredhuling/fastglm/blob/master/src/glm.h and use that header for this purpose. 
All the permutations could be generated in advance using self$mean_function$randomise() as a matrix and passed to this function.

**Comment by samuel-watson** [comment]
Would need to convert from arma to Eigen classes (and back). This doesn't seem too hard, e.g. see accepted answer here: https://stackoverflow.com/questions/46700560/converting-an-armadillo-matrix-to-an-eigen-matrixd-and-vice-versa/46700774
@ypan1988 Do we think worth doing?

**Comment by ypan1988** [comment]
Yes, if we are going to translate the two functions to C++, it is probably the easiest way. I checked some other implementation of GLM using armadillo – not as good as fastglm.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by samuel-watson** [comment]
@ypan1988 For this function do we need to use armadillo though? Can it just be done all in Eigen? I don't think we call any c++ functions in it currently - it's all in R.
